name: lumimi_app
description: App de aprendizado para crianças com necessidades especiais.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependências existentes
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  path_provider: ^2.1.5
  
  # Dependências para autenticação
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.6
  
  # Dependências para relatórios PDF (SEM PRINTING)
  pdf: ^3.11.3
  
  # ALTERNATIVAS AO PRINTING (SEM IMPRESSÃO):
  # Para visualização de PDF
  flutter_pdfview: ^1.3.2          # Visualizar PDFs nativamente
  # OU: pdfx: ^2.4.0               # Alternativa moderna
  # OU: syncfusion_flutter_pdfviewer: ^23.2.7  # Mais robusto
  
  # Para compartilhamento (já estava no pubspec)
  share_plus: ^7.2.1
  cloud_firestore: ^4.17.5
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true