name: lumimi_app
description: App de aprendizado para crianças com necessidades especiais.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependências existentes
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  printing: ^5.13.1
  path_provider: ^2.1.5
  
  # Dependências para autenticação (versões específicas testadas)
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.6
  
  # Dependências para relatórios (opcional, manter comentado por enquanto)
  # pdf: ^3.10.7
  # share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true