name: lumimi_app
description: App de aprendizado para crianças com necessidades especiais.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependências existentes que funcionam
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  printing: ^5.14.2
  path_provider: ^2.1.5
  
  # Dependências para relatórios (adicionar depois quando o app estiver funcionando)
  # pdf: ^3.10.7
  # path_provider: ^2.1.1
  # share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true