name: lulumio
description: "Um aplicativo educativo para crianças"

# Versão do aplicativo
version: 1.0.0+1

environment:
  sdk: ^3.4.0

# Dependências do aplicativo
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  intl: ^0.20.2

# Dependências de desenvolvimento
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Adicionado aqui corretamente

# Configuração do flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffd207"
  adaptive_icon_foreground: "assets/images/logo.png"

# Configurações Flutter
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/