// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3hHpkJBRzvkpaHmPNNc-PSqDwlUK0nTo',
    appId: '1:705064727278:web:3939ff',
    messagingSenderId: '705064727278',
    projectId: 'lumimi-app',
    authDomain: 'lumimi-app.firebaseapp.com',
    storageBucket: 'lumimi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3hHpkJBRzvkpaHmPNNc-PSqDwlUK0nTo',
    appId: '1:705064727278:android:331239c9ac1356df3939ff',
    messagingSenderId: '705064727278',
    projectId: 'lumimi-app',
    storageBucket: 'lumimi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3hHpkJBRzvkpaHmPNNc-PSqDwlUK0nTo',
    appId: '1:705064727278:ios:331239c9ac1356df3939ff',
    messagingSenderId: '705064727278',
    projectId: 'lumimi-app',
    storageBucket: 'lumimi-app.firebasestorage.app',
    iosBundleId: 'com.cogluna.lumimi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3hHpkJBRzvkpaHmPNNc-PSqDwlUK0nTo',
    appId: '1:705064727278:macos:331239c9ac1356df3939ff',
    messagingSenderId: '705064727278',
    projectId: 'lumimi-app',
    storageBucket: 'lumimi-app.firebasestorage.app',
    iosBundleId: 'com.cogluna.lumimi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3hHpkJBRzvkpaHmPNNc-PSqDwlUK0nTo',
    appId: '1:705064727278:windows:331239c9ac1356df3939ff',
    messagingSenderId: '705064727278',
    projectId: 'lumimi-app',
    storageBucket: 'lumimi-app.firebasestorage.app',
  );
}